version: '3.8'
services:
  client:
    image: qamar2315/imaginarium-client-v1:latest
    ports:
      - "3000:80"  # Map host port 3000 to container port 80
  server:
    image: qamar2315/imaginarium-server-v1:latest
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=${MONGODB_URL} # Use your MongoDB connection string
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    secrets:  # Declare that the server needs a secret
      - firebase_credentials
    depends_on: # Ensure MongoDB is running before the server
      - mongodb
    volumes:
      - ./logs/:/app/logs/
  mongodb:
    image: mongo:latest # Or a specific version
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
secrets: 
  firebase_credentials:
    file: ./server/config/serviceAccountKey.json  # Path to your secrets file

volumes:
  mongodb_data: